COMPOUND_ATTRIBUTE_SMELL = "Compound Attribute"
ADJACENCY_LIST = "Adjacency List"
GOD_TABLE = "God Table"
VALUES_IN_COLUMN_DEFINION = "Values in Column Definition"

GOD_TABLE_MAX_COLUMN_THRESHOLD = 10